### PR TITLE
feat: mvp

### PR DESCRIPTION
**Pull request by kelonye**
- staged at https://rebased-token-swap.surge.sh
- includes ability to request tokens from faucet (when not connected to mainnet)

### todos

- [x] cleanup design
- [x] fix transaction completion subscription
- [x] better warning alerts (replace with sweetalert.js for example)
- [ ] support other web3 providers like walletconnect, coinbase wallet
- [x] responsive ux
- [x] config for supported networks and their corresponding contract addresses

### CODE REVIEW

**Comment by nckl3r** [comment]
Thank you @vbstreetz! Would you mind one minor change.. adding a comma to the numbers? For example comma-format 912,122 instead of 912122.

**Comment by kelonye** [comment]
> Thank you @vbstreetz! Would you mind one minor change.. adding a comma to the numbers? For example comma-format 912,122 instead of 912122.

Sure! On it..

**Comment by kelonye** [comment]
> Thank you @vbstreetz! Would you mind one minor change.. adding a comma to the numbers? For example comma-format 912,122 instead of 912122.

hey. i just pushed an update for this.

**Comment by kelonye** [comment]
Looking good on mobile:

**Pull request merged**
